services:
  backend:
    build: ./apps/backend
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
    networks:
      - room-browsing-app

  frontend:
    build: ./apps/frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - backend
    networks:
      - room-browsing-app

networks:
  room-browsing-app:
    driver: bridge
